/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.udt;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.db.udt.records.ValidDetailRecord;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Schema;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.SchemaImpl;
import org.jooq.impl.UDTImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ValidDetail extends UDTImpl<ValidDetailRecord> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>public.valid_detail</code> */
  public static final ValidDetail VALID_DETAIL = new ValidDetail();

  /** The class holding records for this type */
  @Override
  public Class<ValidDetailRecord> getRecordType() {
    return ValidDetailRecord.class;
  }

  /** The attribute <code>public.valid_detail.valid</code>. */
  public static final UDTField<ValidDetailRecord, Boolean> VALID =
      createField(DSL.name("valid"), SQLDataType.BOOLEAN, VALID_DETAIL, "");

  /** The attribute <code>public.valid_detail.reason</code>. */
  public static final UDTField<ValidDetailRecord, String> REASON =
      createField(DSL.name("reason"), SQLDataType.VARCHAR, VALID_DETAIL, "");

  /** The attribute <code>public.valid_detail.location</code>. */
  public static final UDTField<ValidDetailRecord, Geometry<?>> LOCATION =
      createField(
          DSL.name("location"),
          SQLDataType.OTHER,
          VALID_DETAIL,
          "",
          new GeolatteGeometryConverter());

  /** No further instances allowed */
  private ValidDetail() {
    super(DSL.name("valid_detail"), null, null, false);
  }

  @Override
  public Schema getSchema() {
    return Public.PUBLIC != null ? Public.PUBLIC : new SchemaImpl(DSL.name("public"));
  }
}
