/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.minicqrs.demoapp.db.tables;


import be.wegenenverkeer.minicqrs.demoapp.db.Keys;
import be.wegenenverkeer.minicqrs.demoapp.db.Public;
import be.wegenenverkeer.minicqrs.demoapp.db.tables.records.TestProjectionRecord;

import java.util.Collection;
import java.util.UUID;

import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.PlainSQL;
import org.jooq.QueryPart;
import org.jooq.SQL;
import org.jooq.Schema;
import org.jooq.Select;
import org.jooq.Stringly;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class TestProjection extends TableImpl<TestProjectionRecord> {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public.test_projection</code>
     */
    public static final TestProjection TEST_PROJECTION = new TestProjection();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<TestProjectionRecord> getRecordType() {
        return TestProjectionRecord.class;
    }

    /**
     * The column <code>public.test_projection.id</code>.
     */
    public final TableField<TestProjectionRecord, UUID> ID = createField(DSL.name("id"), SQLDataType.UUID.nullable(false), this, "");

    /**
     * The column <code>public.test_projection.counter</code>.
     */
    public final TableField<TestProjectionRecord, Long> COUNTER = createField(DSL.name("counter"), SQLDataType.BIGINT.nullable(false), this, "");

    private TestProjection(Name alias, Table<TestProjectionRecord> aliased) {
        this(alias, aliased, (Field<?>[]) null, null);
    }

    private TestProjection(Name alias, Table<TestProjectionRecord> aliased, Field<?>[] parameters, Condition where) {
        super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.table(), where);
    }

    /**
     * Create an aliased <code>public.test_projection</code> table reference
     */
    public TestProjection(String alias) {
        this(DSL.name(alias), TEST_PROJECTION);
    }

    /**
     * Create an aliased <code>public.test_projection</code> table reference
     */
    public TestProjection(Name alias) {
        this(alias, TEST_PROJECTION);
    }

    /**
     * Create a <code>public.test_projection</code> table reference
     */
    public TestProjection() {
        this(DSL.name("test_projection"), null);
    }

    @Override
    public Schema getSchema() {
        return aliased() ? null : Public.PUBLIC;
    }

    @Override
    public UniqueKey<TestProjectionRecord> getPrimaryKey() {
        return Keys.TEST_PROJECTION_PKEY;
    }

    @Override
    public TestProjection as(String alias) {
        return new TestProjection(DSL.name(alias), this);
    }

    @Override
    public TestProjection as(Name alias) {
        return new TestProjection(alias, this);
    }

    @Override
    public TestProjection as(Table<?> alias) {
        return new TestProjection(alias.getQualifiedName(), this);
    }

    /**
     * Rename this table
     */
    @Override
    public TestProjection rename(String name) {
        return new TestProjection(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestProjection rename(Name name) {
        return new TestProjection(name, null);
    }

    /**
     * Rename this table
     */
    @Override
    public TestProjection rename(Table<?> name) {
        return new TestProjection(name.getQualifiedName(), null);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestProjection where(Condition condition) {
        return new TestProjection(getQualifiedName(), aliased() ? this : null, null, condition);
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestProjection where(Collection<? extends Condition> conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestProjection where(Condition... conditions) {
        return where(DSL.and(conditions));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestProjection where(Field<Boolean> condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestProjection where(SQL condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestProjection where(@Stringly.SQL String condition) {
        return where(DSL.condition(condition));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestProjection where(@Stringly.SQL String condition, Object... binds) {
        return where(DSL.condition(condition, binds));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    @PlainSQL
    public TestProjection where(@Stringly.SQL String condition, QueryPart... parts) {
        return where(DSL.condition(condition, parts));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestProjection whereExists(Select<?> select) {
        return where(DSL.exists(select));
    }

    /**
     * Create an inline derived table from this table
     */
    @Override
    public TestProjection whereNotExists(Select<?> select) {
        return where(DSL.notExists(select));
    }
}
