/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.minicqrs.core.db;


import be.wegenenverkeer.minicqrs.core.db.tables.Journal;
import be.wegenenverkeer.minicqrs.core.db.tables.ProjectionOffset;
import be.wegenenverkeer.minicqrs.core.db.tables.Snapshot;

import java.util.Arrays;
import java.util.List;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Public extends SchemaImpl {

    private static final long serialVersionUID = 1L;

    /**
     * The reference instance of <code>public</code>
     */
    public static final Public PUBLIC = new Public();

    /**
     * The table <code>public.journal</code>.
     */
    public final Journal JOURNAL = Journal.JOURNAL;

    /**
     * The table <code>public.projection_offset</code>.
     */
    public final ProjectionOffset PROJECTION_OFFSET = ProjectionOffset.PROJECTION_OFFSET;

    /**
     * The table <code>public.snapshot</code>.
     */
    public final Snapshot SNAPSHOT = Snapshot.SNAPSHOT;

    /**
     * No further instances allowed
     */
    private Public() {
        super("public", null);
    }


    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        return Arrays.asList(
            Journal.JOURNAL,
            ProjectionOffset.PROJECTION_OFFSET,
            Snapshot.SNAPSHOT
        );
    }
}
