/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.minicqrs.demoapp.db;


import be.wegenenverkeer.minicqrs.demoapp.db.tables.TestProjection;


/**
 * Convenience access to all tables in public.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class Tables {

    /**
     * The table <code>public.test_projection</code>.
     */
    public static final TestProjection TEST_PROJECTION = TestProjection.TEST_PROJECTION;
}
