/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.udt.paths;

import be.wegenenverkeer.geojson.db.udt.ValidDetail;
import be.wegenenverkeer.geojson.db.udt.records.ValidDetailRecord;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Binding;
import org.jooq.Comment;
import org.jooq.DataType;
import org.jooq.Name;
import org.jooq.Record;
import org.jooq.RecordQualifier;
import org.jooq.UDTField;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.UDTPathTableFieldImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class ValidDetailPath<R extends Record, T>
    extends UDTPathTableFieldImpl<R, ValidDetailRecord, T> {

  private static final long serialVersionUID = 1L;

  /** The attribute <code>public.valid_detail.valid</code>. */
  public final UDTField<ValidDetailRecord, Boolean> VALID =
      Internal.createUDTPathField(DSL.name("valid"), SQLDataType.BOOLEAN, this, "", UDTField.class);

  /** The attribute <code>public.valid_detail.reason</code>. */
  public final UDTField<ValidDetailRecord, String> REASON =
      Internal.createUDTPathField(
          DSL.name("reason"), SQLDataType.VARCHAR, this, "", UDTField.class);

  /** The attribute <code>public.valid_detail.location</code>. */
  public final UDTField<ValidDetailRecord, Geometry<?>> LOCATION =
      Internal.createUDTPathField(
          DSL.name("location"),
          SQLDataType.OTHER,
          this,
          "",
          UDTField.class,
          new GeolatteGeometryConverter());

  public ValidDetailPath(
      Name name,
      DataType<T> type,
      RecordQualifier<R> qualifier,
      Comment comment,
      Binding<?, T> binding) {
    super(name, type, qualifier, ValidDetail.VALID_DETAIL, comment, binding);
  }
}
