/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.minicqrs.core.db.tables.records;

import be.wegenenverkeer.minicqrs.core.db.tables.Snapshot;
import org.jooq.JSONB;
import org.jooq.Record2;
import org.jooq.impl.UpdatableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class SnapshotRecord extends UpdatableRecordImpl<SnapshotRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.snapshot.id</code>. */
  public void setId(String value) {
    set(0, value);
  }

  /** Getter for <code>public.snapshot.id</code>. */
  public String getId() {
    return (String) get(0);
  }

  /** Setter for <code>public.snapshot.snapshot</code>. */
  public void setSnapshot(JSONB value) {
    set(1, value);
  }

  /** Getter for <code>public.snapshot.snapshot</code>. */
  public JSONB getSnapshot() {
    return (JSONB) get(1);
  }

  /** Setter for <code>public.snapshot.sequence</code>. */
  public void setSequence(Long value) {
    set(2, value);
  }

  /** Getter for <code>public.snapshot.sequence</code>. */
  public Long getSequence() {
    return (Long) get(2);
  }

  /** Setter for <code>public.snapshot.type</code>. */
  public void setType(String value) {
    set(3, value);
  }

  /** Getter for <code>public.snapshot.type</code>. */
  public String getType() {
    return (String) get(3);
  }

  // -------------------------------------------------------------------------
  // Primary key information
  // -------------------------------------------------------------------------

  @Override
  public Record2<String, String> key() {
    return (Record2) super.key();
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached SnapshotRecord */
  public SnapshotRecord() {
    super(Snapshot.SNAPSHOT);
  }

  /** Create a detached, initialised SnapshotRecord */
  public SnapshotRecord(String id, JSONB snapshot, Long sequence, String type) {
    super(Snapshot.SNAPSHOT);

    setId(id);
    setSnapshot(snapshot);
    setSequence(sequence);
    setType(type);
    resetChangedOnNotNull();
  }
}
