/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.tables.records;

import be.wegenenverkeer.geojson.db.tables.StDump;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StDumpRecord extends TableRecordImpl<StDumpRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type, it may have been
   *     excluded from code generation. If this is a built-in type, you can define an explicit
   *     {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be
   *     turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator
   *     configuration.
   */
  @Deprecated
  public void setStDump(Object value) {
    set(0, value);
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type, it may have been
   *     excluded from code generation. If this is a built-in type, you can define an explicit
   *     {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be
   *     turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator
   *     configuration.
   */
  @Deprecated
  public Object getStDump() {
    return get(0);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached StDumpRecord */
  public StDumpRecord() {
    super(StDump.ST_DUMP);
  }

  /** Create a detached, initialised StDumpRecord */
  public StDumpRecord(Object stDump) {
    super(StDump.ST_DUMP);

    setStDump(stDump);
    resetChangedOnNotNull();
  }
}
