/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.tables.records;

import be.wegenenverkeer.geojson.db.tables.StDumppoints;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StDumppointsRecord extends TableRecordImpl<StDumppointsRecord> {

  private static final long serialVersionUID = 1L;

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type, it may have been
   *     excluded from code generation. If this is a built-in type, you can define an explicit
   *     {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be
   *     turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator
   *     configuration.
   */
  @Deprecated
  public void setStDumppoints(Object value) {
    set(0, value);
  }

  /**
   * @deprecated Unknown data type. If this is a qualified, user-defined type, it may have been
   *     excluded from code generation. If this is a built-in type, you can define an explicit
   *     {@link org.jooq.Binding} to specify how this type should be handled. Deprecation can be
   *     turned off using {@literal <deprecationOnUnknownTypes/>} in your code generator
   *     configuration.
   */
  @Deprecated
  public Object getStDumppoints() {
    return get(0);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached StDumppointsRecord */
  public StDumppointsRecord() {
    super(StDumppoints.ST_DUMPPOINTS);
  }

  /** Create a detached, initialised StDumppointsRecord */
  public StDumppointsRecord(Object stDumppoints) {
    super(StDumppoints.ST_DUMPPOINTS);

    setStDumppoints(stDumppoints);
    resetChangedOnNotNull();
  }
}
