/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.tables.records;

import be.wegenenverkeer.geojson.db.tables.StHexagongrid;
import org.geolatte.geom.Geometry;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StHexagongridRecord extends TableRecordImpl<StHexagongridRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.st_hexagongrid.geom</code>. */
  public void setGeom(Geometry<?> value) {
    set(0, value);
  }

  /** Getter for <code>public.st_hexagongrid.geom</code>. */
  public Geometry<?> getGeom() {
    return (Geometry<?>) get(0);
  }

  /** Setter for <code>public.st_hexagongrid.i</code>. */
  public void setI(Integer value) {
    set(1, value);
  }

  /** Getter for <code>public.st_hexagongrid.i</code>. */
  public Integer getI() {
    return (Integer) get(1);
  }

  /** Setter for <code>public.st_hexagongrid.j</code>. */
  public void setJ(Integer value) {
    set(2, value);
  }

  /** Getter for <code>public.st_hexagongrid.j</code>. */
  public Integer getJ() {
    return (Integer) get(2);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached StHexagongridRecord */
  public StHexagongridRecord() {
    super(StHexagongrid.ST_HEXAGONGRID);
  }

  /** Create a detached, initialised StHexagongridRecord */
  public StHexagongridRecord(Geometry<?> geom, Integer i, Integer j) {
    super(StHexagongrid.ST_HEXAGONGRID);

    setGeom(geom);
    setI(i);
    setJ(j);
    resetChangedOnNotNull();
  }
}
