/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.tables.records;

import be.wegenenverkeer.geojson.db.tables.StSquaregrid;
import org.geolatte.geom.Geometry;
import org.jooq.impl.TableRecordImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StSquaregridRecord extends TableRecordImpl<StSquaregridRecord> {

  private static final long serialVersionUID = 1L;

  /** Setter for <code>public.st_squaregrid.geom</code>. */
  public void setGeom(Geometry<?> value) {
    set(0, value);
  }

  /** Getter for <code>public.st_squaregrid.geom</code>. */
  public Geometry<?> getGeom() {
    return (Geometry<?>) get(0);
  }

  /** Setter for <code>public.st_squaregrid.i</code>. */
  public void setI(Integer value) {
    set(1, value);
  }

  /** Getter for <code>public.st_squaregrid.i</code>. */
  public Integer getI() {
    return (Integer) get(1);
  }

  /** Setter for <code>public.st_squaregrid.j</code>. */
  public void setJ(Integer value) {
    set(2, value);
  }

  /** Getter for <code>public.st_squaregrid.j</code>. */
  public Integer getJ() {
    return (Integer) get(2);
  }

  // -------------------------------------------------------------------------
  // Constructors
  // -------------------------------------------------------------------------

  /** Create a detached StSquaregridRecord */
  public StSquaregridRecord() {
    super(StSquaregrid.ST_SQUAREGRID);
  }

  /** Create a detached, initialised StSquaregridRecord */
  public StSquaregridRecord(Geometry<?> geom, Integer i, Integer j) {
    super(StSquaregrid.ST_SQUAREGRID);

    setGeom(geom);
    setI(i);
    setJ(j);
    resetChangedOnNotNull();
  }
}
