/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.tables;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.db.tables.records.StHexagongridRecord;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Condition;
import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.TableOptions;
import org.jooq.impl.DSL;
import org.jooq.impl.SQLDataType;
import org.jooq.impl.TableImpl;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StHexagongrid extends TableImpl<StHexagongridRecord> {

  private static final long serialVersionUID = 1L;

  /** The reference instance of <code>public.st_hexagongrid</code> */
  public static final StHexagongrid ST_HEXAGONGRID = new StHexagongrid();

  /** The class holding records for this type */
  @Override
  public Class<StHexagongridRecord> getRecordType() {
    return StHexagongridRecord.class;
  }

  /** The column <code>public.st_hexagongrid.geom</code>. */
  public final TableField<StHexagongridRecord, Geometry<?>> GEOM =
      createField(DSL.name("geom"), SQLDataType.OTHER, this, "", new GeolatteGeometryConverter());

  /** The column <code>public.st_hexagongrid.i</code>. */
  public final TableField<StHexagongridRecord, Integer> I =
      createField(DSL.name("i"), SQLDataType.INTEGER, this, "");

  /** The column <code>public.st_hexagongrid.j</code>. */
  public final TableField<StHexagongridRecord, Integer> J =
      createField(DSL.name("j"), SQLDataType.INTEGER, this, "");

  private StHexagongrid(Name alias, Table<StHexagongridRecord> aliased) {
    this(
        alias,
        aliased,
        new Field[] {
          DSL.val(null, SQLDataType.DOUBLE),
          DSL.val(null, SQLDataType.OTHER.asConvertedDataType(new GeolatteGeometryConverter()))
        });
  }

  private StHexagongrid(Name alias, Table<StHexagongridRecord> aliased, Field<?>[] parameters) {
    this(alias, aliased, parameters, null);
  }

  private StHexagongrid(
      Name alias, Table<StHexagongridRecord> aliased, Field<?>[] parameters, Condition where) {
    super(alias, null, aliased, parameters, DSL.comment(""), TableOptions.function(), where);
  }

  /** Create an aliased <code>public.st_hexagongrid</code> table reference */
  public StHexagongrid(String alias) {
    this(DSL.name(alias), ST_HEXAGONGRID);
  }

  /** Create an aliased <code>public.st_hexagongrid</code> table reference */
  public StHexagongrid(Name alias) {
    this(alias, ST_HEXAGONGRID);
  }

  /** Create a <code>public.st_hexagongrid</code> table reference */
  public StHexagongrid() {
    this(DSL.name("st_hexagongrid"), null);
  }

  @Override
  public Schema getSchema() {
    return aliased() ? null : Public.PUBLIC;
  }

  @Override
  public StHexagongrid as(String alias) {
    return new StHexagongrid(DSL.name(alias), this, parameters);
  }

  @Override
  public StHexagongrid as(Name alias) {
    return new StHexagongrid(alias, this, parameters);
  }

  @Override
  public StHexagongrid as(Table<?> alias) {
    return new StHexagongrid(alias.getQualifiedName(), this, parameters);
  }

  /** Rename this table */
  @Override
  public StHexagongrid rename(String name) {
    return new StHexagongrid(DSL.name(name), null, parameters);
  }

  /** Rename this table */
  @Override
  public StHexagongrid rename(Name name) {
    return new StHexagongrid(name, null, parameters);
  }

  /** Rename this table */
  @Override
  public StHexagongrid rename(Table<?> name) {
    return new StHexagongrid(name.getQualifiedName(), null, parameters);
  }

  /** Call this table-valued function */
  public StHexagongrid call(Double size, Geometry<?> bounds) {
    StHexagongrid result =
        new StHexagongrid(
            DSL.name("st_hexagongrid"),
            null,
            new Field[] {
              DSL.val(size, SQLDataType.DOUBLE),
              DSL.val(
                  bounds, SQLDataType.OTHER.asConvertedDataType(new GeolatteGeometryConverter()))
            });

    return aliased() ? result.as(getUnqualifiedName()) : result;
  }

  /** Call this table-valued function */
  public StHexagongrid call(Field<Double> size, Field<Geometry<?>> bounds) {
    StHexagongrid result =
        new StHexagongrid(DSL.name("st_hexagongrid"), null, new Field[] {size, bounds});

    return aliased() ? result.as(getUnqualifiedName()) : result;
  }
}
