/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class _StVoronoi extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public._st_voronoi.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public._st_voronoi.g1</code>. */
  public static final Parameter<Geometry<?>> G1 =
      Internal.createParameter(
          "g1", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public._st_voronoi.clip</code>. */
  public static final Parameter<Geometry<?>> CLIP =
      Internal.createParameter(
          "clip",
          SQLDataType.OTHER.defaultValue(DSL.field(DSL.raw("NULL::geometry"), SQLDataType.OTHER)),
          true,
          false,
          new GeolatteGeometryConverter());

  /** The parameter <code>public._st_voronoi.tolerance</code>. */
  public static final Parameter<Double> TOLERANCE =
      Internal.createParameter(
          "tolerance",
          SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
          true,
          false);

  /** The parameter <code>public._st_voronoi.return_polygons</code>. */
  public static final Parameter<Boolean> RETURN_POLYGONS =
      Internal.createParameter(
          "return_polygons",
          SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("true"), SQLDataType.BOOLEAN)),
          true,
          false);

  /** Create a new routine call instance */
  public _StVoronoi() {
    super("_st_voronoi", Public.PUBLIC, SQLDataType.OTHER, new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(G1);
    addInParameter(CLIP);
    addInParameter(TOLERANCE);
    addInParameter(RETURN_POLYGONS);
  }

  /** Set the <code>g1</code> parameter IN value to the routine */
  public void setG1(Geometry<?> value) {
    setValue(G1, value);
  }

  /**
   * Set the <code>g1</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setG1(Field<Geometry<?>> field) {
    setField(G1, field);
  }

  /** Set the <code>clip</code> parameter IN value to the routine */
  public void setClip(Geometry<?> value) {
    setValue(CLIP, value);
  }

  /**
   * Set the <code>clip</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setClip(Field<Geometry<?>> field) {
    setField(CLIP, field);
  }

  /** Set the <code>tolerance</code> parameter IN value to the routine */
  public void setTolerance(Double value) {
    setValue(TOLERANCE, value);
  }

  /**
   * Set the <code>tolerance</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setTolerance(Field<Double> field) {
    setField(TOLERANCE, field);
  }

  /** Set the <code>return_polygons</code> parameter IN value to the routine */
  public void setReturnPolygons(Boolean value) {
    setValue(RETURN_POLYGONS, value);
  }

  /**
   * Set the <code>return_polygons</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setReturnPolygons(Field<Boolean> field) {
    setField(RETURN_POLYGONS, field);
  }
}
