/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Gettransactionid extends AbstractRoutine<Long> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.gettransactionid.RETURN_VALUE</code>. */
  public static final Parameter<Long> RETURN_VALUE =
      Internal.createParameter("RETURN_VALUE", SQLDataType.BIGINT, false, false);

  /** Create a new routine call instance */
  public Gettransactionid() {
    super("gettransactionid", Public.PUBLIC, SQLDataType.BIGINT);

    setReturnParameter(RETURN_VALUE);
  }
}
