/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StAsencodedpolyline extends AbstractRoutine<String> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_asencodedpolyline.RETURN_VALUE</code>. */
  public static final Parameter<String> RETURN_VALUE =
      Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

  /** The parameter <code>public.st_asencodedpolyline.geom</code>. */
  public static final Parameter<Geometry<?>> GEOM =
      Internal.createParameter(
          "geom", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_asencodedpolyline.nprecision</code>. */
  public static final Parameter<Integer> NPRECISION =
      Internal.createParameter(
          "nprecision",
          SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("5"), SQLDataType.INTEGER)),
          true,
          false);

  /** Create a new routine call instance */
  public StAsencodedpolyline() {
    super("st_asencodedpolyline", Public.PUBLIC, SQLDataType.CLOB);

    setReturnParameter(RETURN_VALUE);
    addInParameter(GEOM);
    addInParameter(NPRECISION);
  }

  /** Set the <code>geom</code> parameter IN value to the routine */
  public void setGeom(Geometry<?> value) {
    setValue(GEOM, value);
  }

  /**
   * Set the <code>geom</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setGeom(Field<Geometry<?>> field) {
    setField(GEOM, field);
  }

  /** Set the <code>nprecision</code> parameter IN value to the routine */
  public void setNprecision(Integer value) {
    setValue(NPRECISION, value);
  }

  /**
   * Set the <code>nprecision</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setNprecision(Field<Integer> field) {
    setField(NPRECISION, field);
  }
}
