/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StAssvg1 extends AbstractRoutine<String> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_assvg.RETURN_VALUE</code>. */
  public static final Parameter<String> RETURN_VALUE =
      Internal.createParameter("RETURN_VALUE", SQLDataType.CLOB, false, false);

  /** The parameter <code>public.st_assvg.geom</code>. */
  public static final Parameter<Geometry<?>> GEOM =
      Internal.createParameter(
          "geom", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_assvg.rel</code>. */
  public static final Parameter<Integer> REL =
      Internal.createParameter(
          "rel",
          SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
          true,
          false);

  /** The parameter <code>public.st_assvg.maxdecimaldigits</code>. */
  public static final Parameter<Integer> MAXDECIMALDIGITS =
      Internal.createParameter(
          "maxdecimaldigits",
          SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("15"), SQLDataType.INTEGER)),
          true,
          false);

  /** Create a new routine call instance */
  public StAssvg1() {
    super("st_assvg", Public.PUBLIC, SQLDataType.CLOB);

    setReturnParameter(RETURN_VALUE);
    addInParameter(GEOM);
    addInParameter(REL);
    addInParameter(MAXDECIMALDIGITS);
    setOverloaded(true);
  }

  /** Set the <code>geom</code> parameter IN value to the routine */
  public void setGeom(Geometry<?> value) {
    setValue(GEOM, value);
  }

  /**
   * Set the <code>geom</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setGeom(Field<Geometry<?>> field) {
    setField(GEOM, field);
  }

  /** Set the <code>rel</code> parameter IN value to the routine */
  public void setRel(Integer value) {
    setValue(REL, value);
  }

  /**
   * Set the <code>rel</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setRel(Field<Integer> field) {
    setField(REL, field);
  }

  /** Set the <code>maxdecimaldigits</code> parameter IN value to the routine */
  public void setMaxdecimaldigits(Integer value) {
    setValue(MAXDECIMALDIGITS, value);
  }

  /**
   * Set the <code>maxdecimaldigits</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setMaxdecimaldigits(Field<Integer> field) {
    setField(MAXDECIMALDIGITS, field);
  }
}
