/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StBuffer1 extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_buffer.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_buffer.geom</code>. */
  public static final Parameter<Geometry<?>> GEOM =
      Internal.createParameter(
          "geom", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_buffer.radius</code>. */
  public static final Parameter<Double> RADIUS =
      Internal.createParameter("radius", SQLDataType.DOUBLE, false, false);

  /** The parameter <code>public.st_buffer.options</code>. */
  public static final Parameter<String> OPTIONS =
      Internal.createParameter(
          "options",
          SQLDataType.CLOB.defaultValue(DSL.field(DSL.raw("''::text"), SQLDataType.CLOB)),
          true,
          false);

  /** Create a new routine call instance */
  public StBuffer1() {
    super("st_buffer", Public.PUBLIC, SQLDataType.OTHER, new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(GEOM);
    addInParameter(RADIUS);
    addInParameter(OPTIONS);
    setOverloaded(true);
  }

  /** Set the <code>geom</code> parameter IN value to the routine */
  public void setGeom(Geometry<?> value) {
    setValue(GEOM, value);
  }

  /**
   * Set the <code>geom</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setGeom(Field<Geometry<?>> field) {
    setField(GEOM, field);
  }

  /** Set the <code>radius</code> parameter IN value to the routine */
  public void setRadius(Double value) {
    setValue(RADIUS, value);
  }

  /**
   * Set the <code>radius</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setRadius(Field<Double> field) {
    setField(RADIUS, field);
  }

  /** Set the <code>options</code> parameter IN value to the routine */
  public void setOptions(String value) {
    setValue(OPTIONS, value);
  }

  /**
   * Set the <code>options</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setOptions(Field<String> field) {
    setField(OPTIONS, field);
  }
}
