/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StConcavehull extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_concavehull.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_concavehull.param_geom</code>. */
  public static final Parameter<Geometry<?>> PARAM_GEOM =
      Internal.createParameter(
          "param_geom", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_concavehull.param_pctconvex</code>. */
  public static final Parameter<Double> PARAM_PCTCONVEX =
      Internal.createParameter("param_pctconvex", SQLDataType.DOUBLE, false, false);

  /** The parameter <code>public.st_concavehull.param_allow_holes</code>. */
  public static final Parameter<Boolean> PARAM_ALLOW_HOLES =
      Internal.createParameter(
          "param_allow_holes",
          SQLDataType.BOOLEAN.defaultValue(DSL.field(DSL.raw("false"), SQLDataType.BOOLEAN)),
          true,
          false);

  /** Create a new routine call instance */
  public StConcavehull() {
    super("st_concavehull", Public.PUBLIC, SQLDataType.OTHER, new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(PARAM_GEOM);
    addInParameter(PARAM_PCTCONVEX);
    addInParameter(PARAM_ALLOW_HOLES);
  }

  /** Set the <code>param_geom</code> parameter IN value to the routine */
  public void setParamGeom(Geometry<?> value) {
    setValue(PARAM_GEOM, value);
  }

  /**
   * Set the <code>param_geom</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setParamGeom(Field<Geometry<?>> field) {
    setField(PARAM_GEOM, field);
  }

  /** Set the <code>param_pctconvex</code> parameter IN value to the routine */
  public void setParamPctconvex(Double value) {
    setValue(PARAM_PCTCONVEX, value);
  }

  /**
   * Set the <code>param_pctconvex</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setParamPctconvex(Field<Double> field) {
    setField(PARAM_PCTCONVEX, field);
  }

  /** Set the <code>param_allow_holes</code> parameter IN value to the routine */
  public void setParamAllowHoles(Boolean value) {
    setValue(PARAM_ALLOW_HOLES, value);
  }

  /**
   * Set the <code>param_allow_holes</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setParamAllowHoles(Field<Boolean> field) {
    setField(PARAM_ALLOW_HOLES, field);
  }
}
