/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StDelaunaytriangles extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_delaunaytriangles.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_delaunaytriangles.g1</code>. */
  public static final Parameter<Geometry<?>> G1 =
      Internal.createParameter(
          "g1", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_delaunaytriangles.tolerance</code>. */
  public static final Parameter<Double> TOLERANCE =
      Internal.createParameter(
          "tolerance",
          SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
          true,
          false);

  /** The parameter <code>public.st_delaunaytriangles.flags</code>. */
  public static final Parameter<Integer> FLAGS =
      Internal.createParameter(
          "flags",
          SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("0"), SQLDataType.INTEGER)),
          true,
          false);

  /** Create a new routine call instance */
  public StDelaunaytriangles() {
    super(
        "st_delaunaytriangles", Public.PUBLIC, SQLDataType.OTHER, new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(G1);
    addInParameter(TOLERANCE);
    addInParameter(FLAGS);
  }

  /** Set the <code>g1</code> parameter IN value to the routine */
  public void setG1(Geometry<?> value) {
    setValue(G1, value);
  }

  /**
   * Set the <code>g1</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setG1(Field<Geometry<?>> field) {
    setField(G1, field);
  }

  /** Set the <code>tolerance</code> parameter IN value to the routine */
  public void setTolerance(Double value) {
    setValue(TOLERANCE, value);
  }

  /**
   * Set the <code>tolerance</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setTolerance(Field<Double> field) {
    setField(TOLERANCE, field);
  }

  /** Set the <code>flags</code> parameter IN value to the routine */
  public void setFlags(Integer value) {
    setValue(FLAGS, value);
  }

  /**
   * Set the <code>flags</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setFlags(Field<Integer> field) {
    setField(FLAGS, field);
  }
}
