/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StGeneratepoints1 extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_generatepoints.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_generatepoints.area</code>. */
  public static final Parameter<Geometry<?>> AREA =
      Internal.createParameter(
          "area", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_generatepoints.npoints</code>. */
  public static final Parameter<Integer> NPOINTS =
      Internal.createParameter("npoints", SQLDataType.INTEGER, false, false);

  /** Create a new routine call instance */
  public StGeneratepoints1() {
    super("st_generatepoints", Public.PUBLIC, SQLDataType.OTHER, new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(AREA);
    addInParameter(NPOINTS);
    setOverloaded(true);
  }

  /** Set the <code>area</code> parameter IN value to the routine */
  public void setArea(Geometry<?> value) {
    setValue(AREA, value);
  }

  /**
   * Set the <code>area</code> parameter to the function to be used with a {@link org.jooq.Select}
   * statement
   */
  public void setArea(Field<Geometry<?>> field) {
    setField(AREA, field);
  }

  /** Set the <code>npoints</code> parameter IN value to the routine */
  public void setNpoints(Integer value) {
    setValue(NPOINTS, value);
  }

  /**
   * Set the <code>npoints</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setNpoints(Field<Integer> field) {
    setField(NPOINTS, field);
  }
}
