/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StLocatebetween extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_locatebetween.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_locatebetween.geometry</code>. */
  public static final Parameter<Geometry<?>> GEOMETRY =
      Internal.createParameter(
          "geometry", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_locatebetween.frommeasure</code>. */
  public static final Parameter<Double> FROMMEASURE =
      Internal.createParameter("frommeasure", SQLDataType.DOUBLE, false, false);

  /** The parameter <code>public.st_locatebetween.tomeasure</code>. */
  public static final Parameter<Double> TOMEASURE =
      Internal.createParameter("tomeasure", SQLDataType.DOUBLE, false, false);

  /** The parameter <code>public.st_locatebetween.leftrightoffset</code>. */
  public static final Parameter<Double> LEFTRIGHTOFFSET =
      Internal.createParameter(
          "leftrightoffset",
          SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
          true,
          false);

  /** Create a new routine call instance */
  public StLocatebetween() {
    super("st_locatebetween", Public.PUBLIC, SQLDataType.OTHER, new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(GEOMETRY);
    addInParameter(FROMMEASURE);
    addInParameter(TOMEASURE);
    addInParameter(LEFTRIGHTOFFSET);
  }

  /** Set the <code>geometry</code> parameter IN value to the routine */
  public void setGeometry(Geometry<?> value) {
    setValue(GEOMETRY, value);
  }

  /**
   * Set the <code>geometry</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setGeometry(Field<Geometry<?>> field) {
    setField(GEOMETRY, field);
  }

  /** Set the <code>frommeasure</code> parameter IN value to the routine */
  public void setFrommeasure(Double value) {
    setValue(FROMMEASURE, value);
  }

  /**
   * Set the <code>frommeasure</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setFrommeasure(Field<Double> field) {
    setField(FROMMEASURE, field);
  }

  /** Set the <code>tomeasure</code> parameter IN value to the routine */
  public void setTomeasure(Double value) {
    setValue(TOMEASURE, value);
  }

  /**
   * Set the <code>tomeasure</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setTomeasure(Field<Double> field) {
    setField(TOMEASURE, field);
  }

  /** Set the <code>leftrightoffset</code> parameter IN value to the routine */
  public void setLeftrightoffset(Double value) {
    setValue(LEFTRIGHTOFFSET, value);
  }

  /**
   * Set the <code>leftrightoffset</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setLeftrightoffset(Field<Double> field) {
    setField(LEFTRIGHTOFFSET, field);
  }
}
