/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StLocatealong extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_locatealong.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_locatealong.geometry</code>. */
  public static final Parameter<Geometry<?>> GEOMETRY =
      Internal.createParameter(
          "geometry", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_locatealong.measure</code>. */
  public static final Parameter<Double> MEASURE =
      Internal.createParameter("measure", SQLDataType.DOUBLE, false, false);

  /** The parameter <code>public.st_locatealong.leftrightoffset</code>. */
  public static final Parameter<Double> LEFTRIGHTOFFSET =
      Internal.createParameter(
          "leftrightoffset",
          SQLDataType.DOUBLE.defaultValue(DSL.field(DSL.raw("0.0"), SQLDataType.DOUBLE)),
          true,
          false);

  /** Create a new routine call instance */
  public StLocatealong() {
    super("st_locatealong", Public.PUBLIC, SQLDataType.OTHER, new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(GEOMETRY);
    addInParameter(MEASURE);
    addInParameter(LEFTRIGHTOFFSET);
  }

  /** Set the <code>geometry</code> parameter IN value to the routine */
  public void setGeometry(Geometry<?> value) {
    setValue(GEOMETRY, value);
  }

  /**
   * Set the <code>geometry</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setGeometry(Field<Geometry<?>> field) {
    setField(GEOMETRY, field);
  }

  /** Set the <code>measure</code> parameter IN value to the routine */
  public void setMeasure(Double value) {
    setValue(MEASURE, value);
  }

  /**
   * Set the <code>measure</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setMeasure(Field<Double> field) {
    setField(MEASURE, field);
  }

  /** Set the <code>leftrightoffset</code> parameter IN value to the routine */
  public void setLeftrightoffset(Double value) {
    setValue(LEFTRIGHTOFFSET, value);
  }

  /**
   * Set the <code>leftrightoffset</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setLeftrightoffset(Field<Double> field) {
    setField(LEFTRIGHTOFFSET, field);
  }
}
