/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StLocatebetweenelevations extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_locatebetweenelevations.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_locatebetweenelevations.geometry</code>. */
  public static final Parameter<Geometry<?>> GEOMETRY =
      Internal.createParameter(
          "geometry", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_locatebetweenelevations.fromelevation</code>. */
  public static final Parameter<Double> FROMELEVATION =
      Internal.createParameter("fromelevation", SQLDataType.DOUBLE, false, false);

  /** The parameter <code>public.st_locatebetweenelevations.toelevation</code>. */
  public static final Parameter<Double> TOELEVATION =
      Internal.createParameter("toelevation", SQLDataType.DOUBLE, false, false);

  /** Create a new routine call instance */
  public StLocatebetweenelevations() {
    super(
        "st_locatebetweenelevations",
        Public.PUBLIC,
        SQLDataType.OTHER,
        new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(GEOMETRY);
    addInParameter(FROMELEVATION);
    addInParameter(TOELEVATION);
  }

  /** Set the <code>geometry</code> parameter IN value to the routine */
  public void setGeometry(Geometry<?> value) {
    setValue(GEOMETRY, value);
  }

  /**
   * Set the <code>geometry</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setGeometry(Field<Geometry<?>> field) {
    setField(GEOMETRY, field);
  }

  /** Set the <code>fromelevation</code> parameter IN value to the routine */
  public void setFromelevation(Double value) {
    setValue(FROMELEVATION, value);
  }

  /**
   * Set the <code>fromelevation</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setFromelevation(Field<Double> field) {
    setField(FROMELEVATION, field);
  }

  /** Set the <code>toelevation</code> parameter IN value to the routine */
  public void setToelevation(Double value) {
    setValue(TOELEVATION, value);
  }

  /**
   * Set the <code>toelevation</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setToelevation(Field<Double> field) {
    setField(TOELEVATION, field);
  }
}
