/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db.routines;

import be.wegenenverkeer.geojson.db.Public;
import be.wegenenverkeer.geojson.util.GeolatteGeometryConverter;
import org.geolatte.geom.Geometry;
import org.jooq.Field;
import org.jooq.Parameter;
import org.jooq.impl.AbstractRoutine;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;
import org.jooq.impl.SQLDataType;

/** This class is generated by jOOQ. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class StMinimumboundingcircle extends AbstractRoutine<Geometry<?>> {

  private static final long serialVersionUID = 1L;

  /** The parameter <code>public.st_minimumboundingcircle.RETURN_VALUE</code>. */
  public static final Parameter<Geometry<?>> RETURN_VALUE =
      Internal.createParameter(
          "RETURN_VALUE", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_minimumboundingcircle.inputgeom</code>. */
  public static final Parameter<Geometry<?>> INPUTGEOM =
      Internal.createParameter(
          "inputgeom", SQLDataType.OTHER, false, false, new GeolatteGeometryConverter());

  /** The parameter <code>public.st_minimumboundingcircle.segs_per_quarter</code>. */
  public static final Parameter<Integer> SEGS_PER_QUARTER =
      Internal.createParameter(
          "segs_per_quarter",
          SQLDataType.INTEGER.defaultValue(DSL.field(DSL.raw("48"), SQLDataType.INTEGER)),
          true,
          false);

  /** Create a new routine call instance */
  public StMinimumboundingcircle() {
    super(
        "st_minimumboundingcircle",
        Public.PUBLIC,
        SQLDataType.OTHER,
        new GeolatteGeometryConverter());

    setReturnParameter(RETURN_VALUE);
    addInParameter(INPUTGEOM);
    addInParameter(SEGS_PER_QUARTER);
  }

  /** Set the <code>inputgeom</code> parameter IN value to the routine */
  public void setInputgeom(Geometry<?> value) {
    setValue(INPUTGEOM, value);
  }

  /**
   * Set the <code>inputgeom</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setInputgeom(Field<Geometry<?>> field) {
    setField(INPUTGEOM, field);
  }

  /** Set the <code>segs_per_quarter</code> parameter IN value to the routine */
  public void setSegsPerQuarter(Integer value) {
    setValue(SEGS_PER_QUARTER, value);
  }

  /**
   * Set the <code>segs_per_quarter</code> parameter to the function to be used with a {@link
   * org.jooq.Select} statement
   */
  public void setSegsPerQuarter(Field<Integer> field) {
    setField(SEGS_PER_QUARTER, field);
  }
}
