/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db;

import be.wegenenverkeer.geojson.db.tables.SpatialRefSys;
import be.wegenenverkeer.geojson.db.tables.records.SpatialRefSysRecord;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.Internal;

/** A class modelling foreign key relationships and constraints of tables in public. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class Keys {

  // -------------------------------------------------------------------------
  // UNIQUE and PRIMARY KEY definitions
  // -------------------------------------------------------------------------

  public static final UniqueKey<SpatialRefSysRecord> SPATIAL_REF_SYS_PKEY =
      Internal.createUniqueKey(
          SpatialRefSys.SPATIAL_REF_SYS,
          DSL.name("spatial_ref_sys_pkey"),
          new TableField[] {SpatialRefSys.SPATIAL_REF_SYS.SRID},
          true);
}
