/*
 * This file is generated by jOOQ.
 */
package be.wegenenverkeer.geojson.db;

import be.wegenenverkeer.geojson.db.udt.GeometryDump;
import be.wegenenverkeer.geojson.db.udt.ValidDetail;

/** Convenience access to all UDTs in public. */
@SuppressWarnings({"all", "unchecked", "rawtypes", "this-escape"})
public class UDTs {

  /** The type <code>public.geometry_dump</code> */
  public static final GeometryDump GEOMETRY_DUMP =
      be.wegenenverkeer.geojson.db.udt.GeometryDump.GEOMETRY_DUMP;

  /** The type <code>public.valid_detail</code> */
  public static final ValidDetail VALID_DETAIL =
      be.wegenenverkeer.geojson.db.udt.ValidDetail.VALID_DETAIL;
}
